stages:
  - deploy

# cache:
#  paths:
#   - node_modules/

deploy:
  image: node
  stage: deploy

  script:
    - npm update
    - npm run-script build
    - echo "$DEVJ_SSH_KEY" > devj.ppk
    - chmod 400 devj.ppk
    - ssh devj@devj.io -T -p $SSH_PORT -o StrictHostKeyChecking=no -i devj.ppk 
      "rm -rf /home/devj/nginx/html/admin/*"
    - scp -P $SSH_PORT -o StrictHostKeyChecking=no -i devj.ppk -r build/* devj@devj.io:/home/devj/nginx/html/admin
  tags:
   - Docker
