stages:
  - deploy

# cache:
#  paths:
#   - node_modules/

deploy:
  image: node
  stage: deploy

  script:
    - npm update
    - npm run-script build
    - echo "$DAEKGIL_SSH_KEY" > daekgil.ppk
    - chmod 400 daekgil.ppk
    - ssh daekgil@devj.io -T -p $SSH_PORT -o StrictHostKeyChecking=no -i daekgil.ppk 
      "rm -rf /home/daekgil/nginx/html/admin/*"
    - scp -P $SSH_PORT -o StrictHostKeyChecking=no -i daekgil.ppk -r build/* daekgil@devj.io:/home/daekgil/nginx/html/admin
  tags:
   - Docker
